<?php

namespace Rederrik\StocksBundle\Repository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySymbol($symbol)
    {
        return $this->createQueryBuilder('s','s.symbol')
            ->where('s.symbol in (:symbol)')
            ->setParameter('symbol',$symbol)
            ->getQuery()
            ->execute();
    }
}
